apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::932854084413:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UD15NPRZN6A4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::932854084413:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-15T18:44:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1395"
  uid: 25cba55d-bc95-4004-9a29-6903c0060850
